<a href="https://colab.research.google.com/github/Venkad000/SCL/blob/main/ws2scl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
from sympy import *

In [ ]:
def power_iteration(A, num_simulations: int):
    b_k = np.random.rand(A.shape[1])
    for _ in range(num_simulations):
        b_k1 = np.dot(A, b_k)
        b_k1_norm = np.linalg.norm(b_k1)
        b_k = b_k1 / b_k1_norm
    return b_k

print(power_iteration(np.array([[4,0,1],[-2,1,0],[-2,0,1]]), 10000))

[ 0.57735027 -0.57735027 -0.57735027]


In [ ]:
from numpy.linalg import eig
a = np.array([[3,-1,0],[-1,2,-1],[0,-1,3]])
w,arr=eig(a)
warrs = arr
dia = False

for i in range(0,len(arr)):
  if (arr[i][i] == 0):
    print("Not diagonalizable")
    break
  else:
    arr[i] = [k / arr[i][i] for k in arr[i]]
  for j in range(0,len(arr)):
    if i != j:
      arr[j] = [x - arr[j][i] * y for x,y in zip(arr[j],arr[i])]
dia = True
print("Diagonizable")

if (dia):
  for i in range(0,len(arr)):
    arr[i][i] = w[i]

  p = []
  for i in warrs:
    p.append(list(i))

print()
print("Matrix after diagonalization:")
print(arr)



Diagonizable

Matrix after diagonalization:
[[1. 0. 0.]
 [0. 3. 0.]
 [0. 0. 4.]]


In [ ]:
p1,d1 = Matrix(a).diagonalize()
print(d1)


Matrix([[1, 0, 0], [0, 3, 0], [0, 0, 4]])


In [ ]:
import re

In [ ]:
eq = "1x2 + 7y2 + -3z2 + 4xy - 2xz + 8yz"
x2_c = re.findall("[^0-9]*([0-9]*?)x2",eq)
y2_c = re.findall("[^0-9]*([0-9]*?)y2",eq)
z2_c = re.findall("[^0-9]*([0-9]*?)z2",eq)
xy_c = re.findall("[^0-9]*([0-9]*?)xy",eq)
xz_c = re.findall("[^0-9]*([0-9]*?)xz",eq)
yz_c = re.findall("[^0-9]*([0-9]*?)yz",eq)

x2_c = int(x2_c[0])
y2_c = int(y2_c[0])
z2_c = int(z2_c[0])
xz_c = int(xz_c[0])
xy_c = int(xy_c[0])
yz_c = int(yz_c[0])

m = [[x2_c,1/2*xy_c,1/2*xz_c],[1/2*xy_c,y2_c,1/2*yz_c],[1/2*xz_c,1/2*yz_c,z2_c]]

print(m)
s,sarr=eig(m)
print(s)
print()
can_eq = ""
can_eq += str(s[0]) + "x2 + "
can_eq += str(s[1]) + "y2 + "
can_eq += str(s[2]) + "z2"
print(can_eq)

[[1, 2.0, 1.0], [2.0, 7, 4.0], [1.0, 4.0, 3]]
[10.02211882  0.2901837   0.68769748]

10.022118817542701x2 + 0.29018370008469235y2 + 0.6876974823726044z2


In [ ]:
import math

In [ ]:
def eq(x):
  # return (3 * x + math.cos(x) - x)
  # return (math.cos(x) - x * math.exp(x))
  # return x**3 - x - 2
  # return (x**3 + 2*x**2 + 10*x - 20)
  # return (x - math.cos(x))
  # return (x - math.sin(x) - 0.5)
  # return (3 * x - math.sin(x) - math.exp(x))
  return (x*math.exp(x) - 3)

In [ ]:
n = 1
max_iter = 1000000
a = 1
b = 2
while (n <= max_iter):
  c = (a+b)/2
  if (eq(c) == 0 or abs(b-a) < 0.5):
    print(eq(c))
    print(c)
    break
  n = n+1
  if (eq(a) * eq(c) > 0):
    a = c
  else:
    b = c


0.46524395503278493
1.125


In [ ]:
n = 1
max_iter = 100000
a = 1
b = 2
while (n <= max_iter):
  c = (a * eq(b) - b * eq(a))/(eq(b) - eq(a))
  if (eq(c) == 0 or abs(b-a) < 0.005):
    print(eq(c))
    print(c)
    break
  n = n+1
  if (eq(a) * eq(c) >= 0):
    a = c
  else:
    b = c

In [ ]:
import sympy

In [ ]:
expr = 